### ISSUE TITLE
Migrate away from attaching finalizers to pointer objects

### ISSUE THREAD

**Issue by jonasfj** [google/webcrypto.dart#10]
See: https://github.com/dart-lang/sdk/issues/45072

We'll have to refactor code like:
https://github.com/google/webcrypto.dart/blob/6dd34605b16097f2845742e04cce1aa4854b07d8/lib/src/impl_ffi/impl_ffi.utils.dart#L29-L37

As the finalizer will need to be attached to an object that isn't `Pointer`, hence, either we'll probably need to wrap with a `EVP_PKEYResource` or something like that.

**Comment by mrcsh** [comment]
I assume this is the cause of the following error that just showed up after updating to Flutter version 2.3.0-24.1.pre?
```I/flutter (14196): ERROR 11:47:23.000:CryptoBloc._emitError/249:<CryptoBloc>Exception: Assertion failed: "package:webcrypto failed to attached finalizer"
I/flutter (14196): INFO 11:47:23.001:CryptoBloc.emit/168:CryptoState(status:CryptoStatus.error, error=Exception: Assertion failed: "package:webcrypto failed to attached finalizer", keyPair=no) #0      _attachFinalizerEVP_PKEY (package:webcrypto/src/impl_ffi/impl_ffi.utils.dart:39:5)
I/flutter (14196): #1      _createEVP_PKEYwithFinalizer (package:webcrypto/src/impl_ffi/impl_ffi.utils.dart:49:3)
I/flutter (14196): #2      _generateRsaKeyPair (package:webcrypto/src/impl_ffi/impl_ffi.rsa_common.dart:287:21)
I/flutter (14196): #3      rsaOaepPrivateKey_generateKey (package:webcrypto/src/impl_ffi/impl_ffi.rsaoaep.dart:68:16)
I/flutter (14196): #4      RsaOaepPrivateKey.generateKey (package:webcrypto/src/webcrypto/webcrypto.rsaoaep.dart:50:12)
I/flutter (14196): #5      _generateRSAKeyRaw (package:common/bloc/crypto/crypto_bloc.dart:52:28)
I/flutter (14196): #6      _generateRSAKey (package:common/bloc/crypto/crypto_bloc.dart:58:24)
I/flutter (14196): #7      _IsolateConfiguration.apply (package:flutter/src/foundation/_isolates_io.dart:81:34)
I/flutter (14196): #8      _spawn.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:88:65)
I/flutter (14196): #9      _spawn.<anonymous clos
E/flutter (14196): [ERROR:flutter/lib/ui/ui_dart_state.cc(213)] Unhandled Exception: Exception: Assertion failed: "package:webcrypto failed to attached finalizer"
E/flutter (14196): #0      _attachFinalizerEVP_PKEY (package:webcrypto/src/impl_ffi/impl_ffi.utils.dart:39:5)
E/flutter (14196): #1      _createEVP_PKEYwithFinalizer (package:webcrypto/src/impl_ffi/impl_ffi.utils.dart:49:3)
E/flutter (14196): #2      _generateRsaKeyPair (package:webcrypto/src/impl_ffi/impl_ffi.rsa_common.dart:287:21)
E/flutter (14196): #3      rsaOaepPrivateKey_generateKey (package:webcrypto/src/impl_ffi/impl_ffi.rsaoaep.dart:68:16)
E/flutter (14196): #4      RsaOaepPrivateKey.generateKey (package:webcrypto/src/webcrypto/webcrypto.rsaoaep.dart:50:12)
E/flutter (14196): #5      _generateRSAKeyRaw (package:common/bloc/crypto/crypto_bloc.dart:52:28)
E/flutter (14196): #6      _generateRSAKey (package:common/bloc/crypto/crypto_bloc.dart:58:24)
E/flutter (14196): #7      _IsolateConfiguration.apply (package:flutter/src/foundation/_isolates_io.dart:81:34)
E/flutter (14196): #8      _spawn.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:88:65)
E/flutter (14196): #9      _spawn.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:87:5)
E/flutter (14196): #10     Timeline.timeSync (dart:developer/timeline.dart:163:22)
E/flutter (14196): #11     _spawn (package:flutter/src/foundation/_isolates_io.dart:85:35)
E/flutter (14196): #12     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:286:17)
E/flutter (14196): #13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter (14196): ```

**Comment by thomnico** [comment]
I can confirm it works when using the code from git, when will it be available in a release ??
