### ISSUE TITLE
Error: Expected a value of type 'JSObject<CryptoKey>', but got one of type 'CryptoKey'

### ISSUE THREAD

**Issue by rahulmuthyam** [google/webcrypto.dart#9]
I've encountered the following error when I was trying to derive a key using the PBKDF2 algorithm for AES Encryption/Decryption on Flutter Web (Beta Channel).

```
static Future<String> generateKey(
  String password,
  String salt,
) async {
  final algo = await Pbkdf2SecretKey.importRawKey(
    utf8.encode(password),
  );
  final key = await algo.deriveBits(
    256,
    Hash.sha256,
    base64.decode(salt),
    65537,
  );
  return base64.encode(key);
}
```

More specifically at `await Pbkdf2SecretKey.importRawKey(...)`.
**EDIT**: This seems to be the case wherever `CryptoKey` is being used.

Here is the link to a sample GitHub project to reproduce the issue: [Repo](https://github.com/rahulmuthyam/flutter-webcrypto-test)

Here are the logs from both the Terminal and the Chrome console.

### Terminal Log
```
Error: Expected a value of type 'JSObject<CryptoKey>', but got one of type 'CryptoKey'
    at Object.throw_ [as throw] (http://localhost:64164/dart_sdk.js:5331:11)
    at Object.castError (http://localhost:64164/dart_sdk.js:5302:15)
    at dart.LazyJSType.new.as (http://localhost:64164/dart_sdk.js:7109:40)
    at Object._argumentErrors (http://localhost:64164/dart_sdk.js:5454:19)
    at Object._checkAndCall (http://localhost:64164/dart_sdk.js:5537:29)
    at Object.dcall (http://localhost:64164/dart_sdk.js:5546:17)
    at ret (http://localhost:64164/dart_sdk.js:60990:21)
```

### Chrome Console Log
```
Uncaught (in promise) Error: Expected a value of type 'JSObject<CryptoKey>', but got one of type 'CryptoKey'
    at Object.throw_ [as throw] (:64807/dart_sdk.js:5331)
    at Object.castError (:64807/dart_sdk.js:5302)
    at dart.LazyJSType.new.as (:64807/dart_sdk.js:7109)
    at Object._argumentErrors (:64807/dart_sdk.js:5454)
    at Object._checkAndCall (:64807/dart_sdk.js:5537)
    at Object.dcall (:64807/dart_sdk.js:5546)
    at ret (:64807/dart_sdk.js:60990)
```

### Flutter Info
```
[✓] Flutter (Channel beta, 1.26.0-17.3.pre, on macOS 11.1 20C69 darwin-x64, locale en-US)
    • Flutter version 1.26.0-17.3.pre at /Users/rahulmuthyam/.flutter
    • Framework revision 4b50ca7f7f (7 days ago), 2021-02-04 19:44:27 -0800
    • Engine revision 2c527d6c7e
    • Dart version 2.12.0 (build 2.12.0-259.8.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/rahulmuthyam/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.150

• No issues found!
```

**Comment by mrcsh** [comment]
I have seen this too and worked around it by commenting out the type check. Will the pr#7 fix this issue?

**Comment by rahulmuthyam** [comment]
Just tested it out, looks like that will fix it.

**Comment by jonasfj** [comment]
Closing this as fixed, thanks.
